### ISSUE TITLE
Planificación 15-01-2016

### ISSUE THREAD

**Issue by sirreal** [coders-cantabria/coders-cantabria#1]
Hay que ir organizando temas para la reunión del 15-01. Sería importante lo siguiente (para empezar):
- Presentación del grupo y las intenciones
- Encuesta sobre intereses, situaciones, historias...
- Contenido...

**Comment by rocimunoz** [comment]
Para que el 15 de Enero llegue esto a la gente, pienso que deberiamos tener las cosas mas o menos listas una semana antes(despues de Reyes) que sera cuando la gente empiece a incorporarse a trabajar y a centrarse de nuevo. 
Difusion via twitter y boca a boca entre nuestros contactos ??
Presentarnos, definir un par de charlas que atraigan a la gente, las encuestas para saber cuales son sus intereses y hacer un poco de networking ese dia.

**Comment by sirreal** [comment]
Totalmente de acuerdo, diria que incluso antes. Me gustaria tener cosas definidas la primera semana de enero para ir captando interes cuanto antes.

Charlas, podemos tirar con #8 y #5. no veo mucho mas opciones ni mucho dialogo :wink:.Espero tener tiempo para preparar #5 durante la próxima semana.

Queda pendiente preparar cuestiones para la encuesta.

**Comment by javiferrero** [comment]
Hola, yo podría preparar una pequeña charla de phantom para el 15 sin
problema. En cuanto a la encuesta y preparación, os parece si nos juntamos
el lunes 4  a las 18:30?

**Comment by rocimunoz** [comment]
El lunes 4 no puedo estar mucho tiempo. Como mucho mucho hasta las 8

**Comment by sirreal** [comment]
Yo no trabajo la semana que viene, así que cuando podáis.

No obstante, creo que la encuesta podremos hacer gran parte aquí:
https://github.com/coders-cantabria/coders-cantabria/blob/master/2015-01-15/encuesta.md

**Comment by rocimunoz** [comment]
Yo hasta el dia 7 estoy de vacaciones. Asi que no tengo demasiados problemas para buscar un hueco

**Comment by javiferrero** [comment]
Hola de nuevo, qué tal veis el juntarnos hoy de 18:30 a 20:00, que es el límite de Rocío? Si preferís otro día, el jueves y viernes también tengo disponibilidad por mi parte (mañana toca cabalgata :( )

**Comment by sirreal** [comment]
Según reunión, aplazamos la 1ª sesión al 5 de febrero: #12
