### ISSUE TITLE
Logotipo

### ISSUE THREAD

**Issue by sirreal** [coders-cantabria/coders-cantabria#11]
Hacer un logotipo para el grupo

**Comment by sirreal** [comment]
Opciones de logotipos en https://github.com/coders-cantabria/coders-cantabria/tree/master/logo

No he hecho nada con color, hay 3 opciones. Acepto comentarios y criticas

**Comment by javiferrero** [comment]
El que más  me gusta es el simple. De los otros 2, lo que menos me llama es la forma de los brackets. 
Me gustan los que aparecen en http://thumb101.shutterstock.com/display_pic_with_logo/1328398/223272577/stock-vector-question-mark-icon-help-symbol-faq-sign-on-a-yellow-background-with-a-triangle-vector-text-in-223272577.jpg
(ojo, todo ésto son mis impresiones, pero no soy ningún experto)

**Comment by sirreal** [comment]
Estoy de acuerdo, la verdad que no me convence mucho ninguno. De momento ponemos el simple, y en un futuro se puede actualizar?

**Comment by javiferrero** [comment]
+1

**Comment by rocimunoz** [comment]
Misma impresion que Javi.

2016-01-17 19:40 GMT+01:00 javiferrero notifications@github.com:
