### ISSUE TITLE
Entrada en coderscantabria.com para primer evento

### ISSUE THREAD

**Issue by sirreal** [coders-cantabria/coders-cantabria#13]
- Lugar y hora
- Contenidos
  - Presentacion
  - Encuesta
  - ...

**Comment by sirreal** [comment]
@rocimunoz Te podrías encargar de hacer este post? ando mal de tiempo. Si no lo hago yo mañana por la mañana

**Comment by rocimunoz** [comment]
Si tranqui, salgo en 1 hora del gimnasio y lo escribo

El lunes, 18 de enero de 2016, Jon Surrell notifications@github.com
escribió:

> @rocimunoz https://github.com/rocimunoz Te podrías encargar de hacer
> este post? ando mal de tiempo. Si no lo hago yo mañana por la mañana
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/coders-cantabria/coders-cantabria/issues/13#issuecomment-172610932
> .

## 

__________________________________________________________________________http://rocixcode.wordpress.com
http://rocixcode.wordpress.com__________________________________________________________________________

**Comment by rocimunoz** [comment]
Creada la entrada al primer evento. ¿Tienen permiso vuestros usuarios para
ver y editar la entrada?

Tiene enlace a la encuesta, explicacion de lo que vamos a hacer, las 2
charlas a tratar.

Queda publicarlo a falta de confirmar la hora que no me quedó claro el otro
dia  (18:00, 18:30??)
Javi, dejo el parroafo de la charla de Phantom para que rellenes con lo que
quieras poner.
Si hay algo que no os gusta, via libre para que cambieis.

Si os parece bien a las 14:00 publicamos y damos difusion.

2016-01-18 22:07 GMT+01:00 Jon Surrell notifications@github.com:

**Comment by sirreal** [comment]
Está muy bien la entrada. He reordenado y cambiado un poco.

Sobre creo que javi cambió a selenium. He puesto un par de líneas sobre ello.

@javiferrero puedes confirmar que hablarás sobre Selenium? y listo para publicar

**Comment by javiferrero** [comment]
Rocío, estoy con Jon, gran entrada :)

Voy a hablar de ambos, de phantom y Selenium. Estoy escribiendo ahora mismo. En 20 minutos está arriba y aviso

**Comment by rocimunoz** [comment]
Genial!!!!

**Comment by javiferrero** [comment]
Listo, @sirreal enlazas a menú o cómo lo mostramos?

**Comment by sirreal** [comment]
Ahora reorganizo un poco.

**Comment by sirreal** [comment]
Ya esta.
