### ISSUE TITLE
Terminar formulario

### ISSUE THREAD

**Issue by sirreal** [coders-cantabria/coders-cantabria#14]
Necesitamos el formulario cuanto antes. Ro empezara a promocionar mañana y tengo que escribir el post para el 1 evento. Queremos poder mandar gente al formulario para que vayan haciendo.

@javiferrero si no te da tiempo, nos avisas y echamos una mano

**Comment by javiferrero** [comment]
Sí, sin problemas, me da tiempo de sobra esta noche.

**Comment by javiferrero** [comment]
Ya está listo, le echáis un ojo?

https://coderscantabria.typeform.com/to/x1ySVM

**Comment by rocimunoz** [comment]
Me encanta la interfaz!!!!!

2016-01-18 22:58 GMT+01:00 javiferrero notifications@github.com:

**Comment by sirreal** [comment]
Genial, no veo problemas.

Lo damos por terminado y podemos incluir enlaces desde la entrada del evento (#13) y en algún tweet.
