### ISSUE TITLE
https en coderscantabria.com

### ISSUE THREAD

**Issue by sirreal** [coders-cantabria/coders-cantabria#15]
https://letsencrypt.org/ ofrece certificados gratis y es relativamente facil de usar.

Pongamos https en coderscantabria.com!

@javiferrero tenemos acceso root para poder hacer eso? Lo puedes compartir conmigo?

**Comment by javiferrero** [comment]
Me temo que en el hosting actual no va a ser posible. Sólo admite un certificado y ya está "ocupado" por otro site...

**Comment by sirreal** [comment]
:frowning: No es gran cosa, pero igual consideramos alternativas. Hablaremos.
