### ISSUE TITLE
¿Cuál es la mejora manera de recopilar charlas y seleccionarlas?

### ISSUE THREAD

**Issue by sirreal** [coders-cantabria/coders-cantabria#17]
De momento estamos recopilando charlas en los issues de este repositorio, y la selección no está muy claro como lo hacemos.

Los issues son adecuados para esto?

La selección se hace a través de "votos"/diálogo en el issues?

Desde luego existen alternativas. Esta manera obliga a todos a tener cuenta en GitHub, que parece un requisito razonable hoy en día. Tampoco es especializado  para votar aunque es factible votar con :+1:

**Comment by MaLKaVeS** [comment]
No parece un mal sistema. A las malas se puede hacer una issue con el día seleccionado y allí votamos de entre las charlas propuestas. 

¿Se podría hacer una votación en la cuenta de twitter?

**Comment by sirreal** [comment]
Veo que si funcionamos asi, necesitamos mas etiquetas. Por ejemplo:

`necesita ponente` - alguien pide un tema de charla pero necesita ponente
`planificado` - está planificado ya para un evento

Y más que se me ocurren. Como se indica que ofrezco una charla, pero queremos saber si interesa? Como medimos el interés que hay para las charlas? Con una etiqueta `para valorar`?

Como ejemplos:
- #18 es `charla`, pero es una petición o ofrecimiento?
- #6 es `charla`, pero es una petición o ofrecimiento?
- #5, #7 y #16 (míos) son temas que ofrezco y quiero opiniones, pero creo que no está claro.

Igual una charla "adjudicada" tiene una persona "asignada" para el issue?

**Comment by sirreal** [comment]
@MaLKaVeS La votación a través de twitter me parece interesante, pero me gustaría que la gente se implicara aquí si vamos a funcionar aquí. Twitter podría resolver dudas más cerca de un evento, por ejemplo decidir entre un par de charlas que están preparadas para el próximo evento.

**Comment by rocimunoz** [comment]
Es cierto no queda claro ... 
La #18 es propuesta pero si no sale nadie seria ofrecimiento. 
Estoy investigando sobre el tema y me parece una pasada. Estoy un poco verde si me tocase hablar de ello ... 
¿Y un plugin de votaciones para wordpress?

**Comment by MaLKaVeS** [comment]
Entonces se podría "valorar" en función del número de participantes. Al que le interese que al menos ponga un "+1" como comentario. Porque no he visto que github tenga una opción para votaciones.

Lo otro tal y como lo comentas parece buena idea.

Si valoráis usar otras herramientas (a parte del wordpress que dice rocio):
- Trello tiene sistema de votaciones. Se crea un tablero y que la gente entre y vote las charlas que se vayan añadiendo.
- slack creo que también tiene la opción y a las malas se podría implementar...

**Comment by sirreal** [comment]
Dentro de WordPress estaría muy bien. Creo que no es tan sencillo como instalar un plugin de encuestas (que hay mil). Hace falte toda la información sobre las charlas que estamos comentando aquí (ponente, tema), y además espacio para comentarlas y gestionarlas. Puede llevar un poco de tiempo.

> Porque no he visto que github tenga una opción para votaciones.

No, aunque la comunidad ha pedido votaciones. Creo que [GitLab](https://about.gitlab.com/) si las tiene, se puede valorar. No tengo experiencia con ello.

En cuanto a slack/trello, igual use trello hace años? Y slack he usado muy poquito. No son más de comunicacion tipo chat, en tiempo real? Cumpliría eso con lo que buscamos? @MaLKaVeS si tienes experiencia con ellos, puedes elaborar un poco?

**Comment by MaLKaVeS** [comment]
Slack es más tipo chat ciertamente, aunque también permite compartir documentos y tiene integraciones con otros servicios como:
- [Github](https://slack.com/apps/A0F7YS2SX-github): This integration will post commits, pull requests, and activity on GitHub Issues to a channel in Slack.
- [Simple Poll](https://slack.com/apps/A0HFW7MR6-simple-poll): A revolutionary slack app that allows you to create native simple polls right within Slack. 

La verdad es que sí podría ser una herramienta más de cara a organización interna si github se quedase corto.

Trello sencillamente son tarjetas y votos: he creado [este panel público de ejemplo](https://trello.com/b/9Rl4yQeN/codercantabria)  con los datos de las charlas que tenemos propuestas.

Este sería un ejemplo de organización (se puede crear aquí la issue y luego añadir el enlace a la tarjeta del Trello y allí poner los votos)

Editando: Acabo de ver lo de GitLab y es de pago (igual hacen descuento para organizaciones ?). Trello y Slack son gratuitas a día de hoy. Trello creo que tiene intención de mantener siempre el tier gratuito.

Sobre el plugin de wordpress, si es simple, volcar la información de la issue a un post tampoco será tan complicado (esto para los de PHP ;P)

**Comment by rocimunoz** [comment]
Y un doodle enganchado a github o a la web??
Para decisiones entre amigos lo usaba hace tiempo. Se puede personalizar al tipo de decision que se necesite. 
https://doodle.com/es/programa-para-votar

No se si la version gratuita nos da para nuestras necesidades

**Comment by sirreal** [comment]
> Acabo de ver lo de GitLab y es de pago

@MaLKaVeS seguro? Acabo de hacer una cuenta gratuita... Lo que no se es el soporte para organizaciones o si se adaptara mejor a nuestras necesidades

**Comment by MaLKaVeS** [comment]
Lo del doodle ni lo conocía. Pero tiene buena pinta.

Efectivamente, Gitlab es de pago si te creas tu servidor, no si usas su alojamiento. Vi lo de pricing y no leí más.
