### ISSUE TITLE
Recopilación de materiales 05-02-2016

### ISSUE THREAD

**Issue by sirreal** [coders-cantabria/coders-cantabria#19]
@rocimunoz 
@javiferrero 

Tenéis los materiales de las charles disponibles? Las podemos meter publicos en esta organización github?

**Comment by javiferrero** [comment]
Por mí sí, ¿dónde los dejamos?

**Comment by rocimunoz** [comment]
Si, sin problemas (codigo y slides)

**Comment by sirreal** [comment]
Buena pregunta. Repositorios independientes dentro de esta organizacion? Teneis permisos para crear repos aqui?

Igual prefijos con `charla-`?

**Comment by rocimunoz** [comment]
No veo boton para crear repositorios.

**Comment by sirreal** [comment]
@rocimunoz Te he intentado invitar como miembro de la org. Te suena? Si aceptas, podrás. Creo que @javiferrero ya puede
