### ISSUE TITLE
Creación de página del grupo

### ISSUE THREAD

**Issue by sirreal** [coders-cantabria/coders-cantabria#2]
Crear una página.

**Comment by javiferrero** [comment]
¿Os parecería hacerlo en un wp tirando de un theme o preferís otra opción?

**Comment by sirreal** [comment]
La prioridad es tener una portada donde podemos publicar información del primer evento y información del grupo. Pensaba crear algo simple y estático tirando del dominio que nos da GitHub. Es gratis y rapido. Creo que deberíamos tenerlo cuanto antes (enero).

Dicho eso, Wordpress está muy bien y aporta mucha funcionalidad, y después de hacer algo simple y estático, normalmente acabo pensando que lo tenía que haber hecho con un CMS. Habría que buscar otra solución para alojamiento, posiblemente con un 3º como [wordpress.com](http://wordpress.com) o [ghost.org](http://ghost.org).

Estoy abierto a cualquier solución, de momento lo que sea más rápido y sencillo, siempre se puede ir a más.

Tenemos algún dotado de diseño, o sabemos de recursos de diseño que podamos incorporar fácilmente?

**Comment by rocimunoz** [comment]
En CantabriaTic tiramos de un wordpress con cuentas de usuario para cada uno y un administrador que lleva el control de todo. 
Tampoco sabemos el tiron que va a tener esto. 
Yo empezaria con un wordpress.

**Comment by sirreal** [comment]
OK para wordpress. Teneis entorno para ello? Alojamiento?

Si no, lo puedo hacer yo, pero hasta dentro de un par de dias nada. Conoceis buenos temas? Yo practicamente no he usado temas (los hacemos a mano).

**Comment by sirreal** [comment]
Hasta que tengamos WP: https://github.com/coders-cantabria/coders-cantabria.github.io

**Comment by javiferrero** [comment]
Nosotros también solemos hacer los temas desde 0, pero, aunque hemos
utilizado algunos, entiendo que aquí necesitaríamos alguno one page por
simplificar. El hosting lo podríamos poner nosotros, incluso no vería
problema en tener un sponsor de Siteground o similar pero más a futuro.

**Comment by javiferrero** [comment]
Íbamos a montar el site de wordpress. pero nos falta dominio. Cuál pillamos?

**Comment by sirreal** [comment]
Podemos tirar con el de github de momento: 

http://coders-cantabria.github.io/

Lo podemos redireccionar:
https://help.github.com/articles/adding-a-cname-file-to-your-repository/

Pensaba empezar con esto y si vamos bien, coger un dominio nuestro.

**Comment by javiferrero** [comment]
Perfecto, no sabía que se podía hacer ese CNAME, tiramos así.

http://larefactoria.com/

En cumplimiento de la Ley de Servicios de la Sociedad de la Información y
del Comercio electrónico 34/2002 de 11 de julio y de la Ley Orgánica de
Protección de Datos 15/1999 de 13 de diciembre, le informamos que su
dirección de correo electrónico ha sido obtenida de nuestro fichero de
clientes que se encuentra debidamente inscrito en la Agencia Española de
Protección de Datos.Este mensaje va dirigido, de manera exclusiva, a su
destinatario y contiene información confidencial y sujeta al secreto
profesional, cuya divulgación no está permitida por la ley. En caso de
haber recibido este mensaje por error, le rogamos que, de forma inmediata,
nos lo comunique mediante correo electrónico remitido a nuestra atención o
a través del teléfono 942766977 y proceda a su eliminación, así como a la
de cualquier documento adjunto al mismo. Asimismo, le comunicamos que la
distribución, copia o utilización de este mensaje, o de cualquier documento
adjunto al mismo, cualquiera que fuera su finalidad, están prohibidas por
la ley.

**Comment by rocimunoz** [comment]
yo tampoco lo sabia.
Me falta experiencia en GitHub :p

Me parece bien

**Comment by javiferrero** [comment]
Ya está instalado el wordpress en http://coders-cantabria.github.io pero redirecciona al subdominio que hemos creado nosotros. Pensaba que el CNAME de github no haría una redirección, sino que funcionaría como alias de dominio. Así que creo que no nos libramos de tener que comprar un dominio, cómo lo veis?

**Comment by rocimunoz** [comment]
Por mi OK, es un gasto asumible

**Comment by sirreal** [comment]
He pillado [coderscantabria.com](http://coderscantabria.com).

Dime el DNS y lo configuro.

**Comment by sirreal** [comment]
37.60.245.153 es OK? O hago CNAME a skynet.larefactoria.com ?

**Comment by javiferrero** [comment]
nameservers: 
dns01.larefactoria.com 
dns02.larefactoria.com

**Comment by sirreal** [comment]
Creo que ya está. No sé cuanto tardará en actualizar...

**Comment by sirreal** [comment]
Bueno, El WP está instalado, deberíamos crear un usuario para cada uno.

Los deberes de esta semana era buscar 2 temas.

No me ha emocionado ninguno. He instalado "tonal" ya, es el que a mi me ha gustado. Es muy simple.

**Comment by rocimunoz** [comment]
Yo tambien estuve ayer buscando alguna plantilla gratis y decente y no sali
muy convencida.

Os pongo el link de las mas decente de las que encontré

Starter
http://demo.themeum.com/#starter

Activello
https://colorlib.com/activello/

Sparkling
https://colorlib.com/sparkling/

BigBrother
https://bigbrotherdemo.wordpress.com/

Argent
https://argentdemo.wordpress.com/

**Comment by javiferrero** [comment]
Yo he visto un par de ellas:
https://wordpress.org/themes/material-gaze/
http://gentsthemes.com/demo/stanleywp/

Me he centrado en este tipo de diseños porque no tenemos fotazas para poner en la cabecera.

De todas formas, creo que tonal cumple a la perfección con su cometido. ¿Qué os parece si nos quedamos con ella y si el tiempo lo permite para dentro de un par de meses miramos una alternativa?

**Comment by sirreal** [comment]
Mi voto sería para Stanley. Como se va pasando el tiempo me lancé a descargar/instalar/activarlo.

Si queréis votar o cambiar, ningún problema. Es por ir agilizando.

Javi, pudiste escribir algo? Te echamos una mano?

**Comment by rocimunoz** [comment]
Mi voto va para Stanley y BigBrother

**Comment by javiferrero** [comment]
Perfecto, nos quedamos pues con Stanley.
No he podido escribir nada, atasco monumental :(

**Comment by sirreal** [comment]
echar un vistazo a [la pagina](http://coderscantabria.com/wp-admin/post.php?post=13&action=edit) que he hecho. Es un texto breve que me salio asi, pero mi sensacion es que capta un poco lo que queremos

comentarios criticas y demas... Corregir lo necesario

**Comment by rocimunoz** [comment]
OK, quito la frase que has dejado a medias "Entendemos que los miembros de
esta comunidad..."
Y ordeno esta frase
_Desarrolladores,, programadores aficionados, coders, programadores,
ingenieros informáticos y cualquiera que tenga interés en temas relacionado
al desarrollo informático y ganas de relacionarse con otros similares._
Me suena mejor asi
_Desarrolladores, coders, programadores, ingenieros informáticos,
aficionados y cualquiera que tenga interés en temas relacionados al
desarrollo informático y ganas de relacionarse con otros similares._

2016-01-18 10:04 GMT+01:00 Jon Surrell notifications@github.com:

**Comment by javiferrero** [comment]
He cambiado la última frase, para quitar dureza al "exigimos": El único requisito es que sientas pasión por el código.

Por lo demás, yo lo compro, he aplicado los cambios de Rocío.

**Comment by rocimunoz** [comment]
Me sale un 404 al entrar con mi usuario.

[image: Imágenes integradas 1]

**Comment by sirreal** [comment]
es porque no hay nada publicado. voy a publicar esta pagina ya
