### ISSUE TITLE
Nombre

### ISSUE THREAD

**Issue by sirreal** [coders-cantabria/coders-cantabria#3]
Ideas para mejores nombres? **Desarrolladores de Cantabria** no es demasiado llamativo y no sé si capta nuestra "esencia".

**Comment by rocimunoz** [comment]
Code Lab Cantabria  (seriamos como un laboratorio de codigo)

**Comment by sirreal** [comment]
Me gusta Code, es mas corto, mas informal, igual mas llamativo? Aunque me gustaria centrar en la gente, al final la idea es comunidad.

Que te parecen:

Coders Cantabria?
Coders de Cantabria?

**Comment by rocimunoz** [comment]
Coders Cantabria me gusta :p

**Comment by sirreal** [comment]
@javiferrero tienes alguna opinión al respecto?

**Comment by javiferrero** [comment]
@sirreal por mí perfecto, suena bien :)
