### ISSUE TITLE
Cuenta twitter

### ISSUE THREAD

**Issue by sirreal** [coders-cantabria/coders-cantabria#4]
Pending #3

**Comment by javiferrero** [comment]
Teniendo nombre, podríamos ir pillando @coderscantabria o @coders_cantabria ¿Cómo haríamos la gestión de Twitter? (aviso, si veis mi número de tweets, veréis que no es mi fuerte)

**Comment by sirreal** [comment]
Cogería @coderscantabria, pero quizá esperar a tener la cuenta de correo (#9).

**Comment by rocimunoz** [comment]
gmail seria lo mas sencillo quiza

**Comment by sirreal** [comment]
[@CodersCantabria](https://twitter.com/coderscantabria)
