### ISSUE TITLE
IOT con Raspberry Pi, Python y automatas

### ISSUE THREAD

**Issue by sirreal** [coders-cantabria/coders-cantabria#6]
Posible charla de uno de ClickArmy

**Comment by rocimunoz** [comment]
Raspberry Pi me interesa aprender cosas. He comprado una y estoy aprendiendo poco a poco

**Comment by MaLKaVeS** [comment]
¡También se puede usar la raspberry con windows 10! Yo de winIoT puedo hablar un poquito (en cuanto me llegue la rasp 2b)
