### ISSUE TITLE
Spring Batch (Java)

### ISSUE THREAD

**Issue by rocimunoz** [coders-cantabria/coders-cantabria#8]
Puedo contaros como trabajamos con procesamiento de datos usando Spring Batch
- lo que es un step
- lo que es un job
- concepto de chunk (reader, proccessor, writer)
- como gestionamos las transacciones

**Comment by sirreal** [comment]
Son cosas que me suenan, pero desconozco por completo, lo cual me parece interesante. ¿Puedes preparar para la primera sessión (#1)?

**Comment by rocimunoz** [comment]
Si, sin problemas.

**Comment by sirreal** [comment]
Planificado para el 5 febrero
